# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy brfimatra.se

on:
  push:
    branches: [ main ]

jobs:
  client-build:

    runs-on: ubuntu-latest
    env:
      working_dir: ./
      out_dir: ./out/
      ftp_host: ${{ secrets.FTP_HOST }}
      ftp_user: ${{ secrets.FTP_USER }}

    steps:
    - uses: actions/checkout@v2
    - name: Client use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
        
    - name: Install dependencies
      run: yarn
      working-directory: ${{ env.working_dir }}
      
    - run: yarn export
      working-directory: ${{ env.working_dir }}
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ env.ftp_host }}
        username: ${{ env.ftp_user }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ${{ env.out_dir }}
