# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy brfimatra.se

on:
  push:
    branches: [ main ]

jobs:
  client-build:

    runs-on: ubuntu-latest
    env:
      working_dir: ./
      out_dir: ./out/

    steps:
    - uses: actions/checkout@v3
    - name: Client use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Install dependencies
      run: yarn
      working-directory: ${{ env.working_dir }}
      
    - run: yarn export
      working-directory: ${{ env.working_dir }}

    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: ssh.brfimatra.se
        remote-user: brfimatra.se
        private-ssh-key: ${{ secrets.SSH_KEY }}
        destination-path: ~/www/
        source-path: ${{ env.out_dir }}
