# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  client-build:

    runs-on: ubuntu-latest
    env:
      working_dir: ./

    steps:
    - uses: actions/checkout@v3
    - name: Client use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
        
    - name: Install dependencies
      run: yarn
      working-directory: ${{ env.working_dir }}
      
    - run: yarn build
      working-directory: ${{ env.working_dir }}

      env:
        CI: true
